---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - feast.dev
  resources:
  - featurestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - feast.dev
  resources:
  - featurestores/finalizers
  verbs:
  - update
- apiGroups:
  - feast.dev
  resources:
  - featurestores/status
  verbs:
  - get
  - patch
  - update
